#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
##  zipkin:
##    base-url: http://localhost:9411/
##
##sleuth:
##  sampler:
##    probability: 1 #100% (default = 10%)
#
#  cloud:
#    gateway:
#      routes:
#        - id: CustomerModule
#          uri: http://localhost:8090/
#          predicates:
#            - Path=/customers/**
#        - id: BookCommandModule
#          uri: http://localhost:8092/
#          predicates:
#            - Path=/books/**
#        - id: BookCommandModule2
#          uri: http://localhost:8091/
#          predicates:
#            - Path=/books/**
#        - id: BookQueriesModule
#          uri: http://localhost:8093/
#          predicates:
#            - Path=/books/get/**
#        - id: BorrowingsModule
#          uri: http://localhost:8095/
#          predicates:
#            - Path=/borrowings/**
#        - id: ReviewModule
#          uri: http://localhost:8094/
#          predicates:
#            - Path=/reviews/**
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,
#        http://localhost:8762/eureka/
