server:
  port: 8888
spring:
 cloud:
  config:
    server:
     git:
      uri: https://github.com/Abiexx/springcloud.git

#  server.port= 8888
#
#  spring.cloud.config.server.git.uri=https://github.com/Abiexx/springcloud.git