server:
  port: 8762

  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

eureka:
   instance:
     hostname: EurekaServer2
     appname: Eureka-cluster
   environment: local
   client:
      serviceUrl:
        defaultZone:
                http://EurekaServer1:8761/eureka
      register-with-eureka: true
      fetch-registry: true



